// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmvziindjfssrntjtaix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tdnppaW5kamZzc3JudGp0YWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTI5MTksImV4cCI6MjA3MzYyODkxOX0.T-06bdYXhzR8x0XSTE4F2p4aYwM4qjaBF4llVkmMPJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});