// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apkdjwngswwqrlovmrcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwa2Rqd25nc3d3cXJsb3ZtcmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjQ3NDYsImV4cCI6MjA3NDY0MDc0Nn0.sqdhXOBj_LWblUPCXBl-CMPG3ThbvPZixQJYg_FRxiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});